### ISSUE TITLE
현재 CPU 를 코어 아이디별로 할당해주고 있는걸 share사용 필요

### ISSUE THREAD

**Issue by ghost** [kmubigdata/ubuntu-spark#1]
특정코어를 할당해주는것 (static scheduling) 이 효율성 면에서 좋지 않으니,
상대적 share 를 정해주는 걸로 스크립트를 업데이트 필요.

https://docs.docker.com/engine/reference/run/#cpu-share-constraint

**Comment by KimJeongChul** [comment]
교수님 spark2.2.1 hadoop2.7.3로 setup 할 것 같습니다.
hadoop yarn으로 cluster 설정시 slave 44개를 생성하여 hadoop2.7-image로 빌드하고
master는 spark-hadoop image로 빌드할 예정입니다.
container 생성 시에는 특정 cpu 코어로 할당하는 --cpuset-cpus=0,1 옵션을 빼고,
--cpu-shares 옵션을 줄 것 같습니다.
--cpu-shares 옵션은 host machine의 CPU cycles에 대한 비율로 나와 있는데 default 값은 1024라고 합니다.

https://www.evernote.com/l/AngGCFPg8C9AJbDe00sw0ziE5nF4get9DGY
https://www.evernote.com/l/AniyLX6yZKVKt64-PmUM63Kob_50nSjkUXg

**Comment by hyu-leeky** [comment]
응 괜찮아 보인다. 슬레이브는 3대 호스트 기기이니까 대당 15개씩 해서 45개로 하는게 계산이 더 편할듯.

**Comment by hyu-leeky** [comment]
https://github.com/kmubigdata/ubuntu-hadoop/blob/master/run_hadoop

이파일을 보니 업데이트가 완료된듯. 수고했어~
