### ISSUE TITLE
Container에서 Spark-Shell을 통해 DistributedMatrix 실행 시 OutOfMemory 발생

### ISSUE THREAD

**Issue by KimJeongChul** [kmubigdata/ubuntu-spark#11]
![2](https://cloud.githubusercontent.com/assets/10591350/26337182/f7fe104c-3fb1-11e7-8686-1d02e3a9e67b.jpeg)

ERROR scheduler.LiveListenerBus: SparkListenerBus has already stopped! Dropping event SparkListenerTaskEnd(5,0,ShuffleMapTask,ExceptionFailure(java.lang.OutOfMemoryError,Java heap space,[Ljava.lang.StackTraceElement;@1fabb000,java.lang.OutOfMemoryError: Java heap space

**Comment by hyu-leeky** [comment]
우선 작은 메트릭스 사이즈로 만들어서 실험해봐. 보통 Out of memory 는 시스템 메모리가 작아서 발생하는 거고.
어떻든 다커랑 호스트 기기랑 메모리 사용에서 생각지 못했던 문제가 발생하고 있는것 같아 - 호스트 기기의 swap 영역을 사용한 문제가 있는것 같아서 우선 swap 사용하는걸 막아뒀으니, 여러 알고리즘 한번 테스트해보고, 문제 없는것 같으면 이슈 close 하자 
https://github.com/kmu-bigdata/distributed-matrix-completion/blob/master/spark_square_matrix_matmul.scala

**Comment by hyu-leeky** [comment]
아침에 확인해보니 다시 비슷한 문제가 발생하네.. 조금더 살펴봐야겠다.

**Comment by namnam21** [comment]
![2017-05-24 2 48 09](https://cloud.githubusercontent.com/assets/22073662/26385701/7a7e52aa-407c-11e7-8301-af2679ccc6b8.png)
spark-shell 에서는 sc를 호출할 때 SparkContext가 자동으로 생성되는걸로 알고있는데 이런 경우도 발생합니다.

**Comment by hyu-leeky** [comment]
하둡 버전 업데이트로 해결
