### ISSUE TITLE
root 계정외에 계정 추가 및 ssh 로 접근 기능 추가 필요

### ISSUE THREAD

**Issue by hyu-leeky** [kmubigdata/ubuntu-spark#4]
현재 bd-3 에서 동작중인 spark-client 의 경우 docker run 을 통해서 root 계정으로만 접근가능해보임.
이는 컨테이너 사용방식 및 계정관리 관련해서 좋은 방법이 아닌것으로 보이니,
각 이미지에 테스트 계정을 하나 만들고, 해당 계정으로 ssh 가능하도록 하는게 좋을듯

**Comment by KimJeongChul** [comment]
docker 실행시 포트포워딩을한다. -p 2200X:2200X
$ sudo docker run -it --name spark-client --network spark-net --ip 10.0.2.49 -p 22006:22006 --add-host=master:10.0.2.2 --cpu-shares 1024 --memory 12g kmubigdata/ubuntu-spark /bin/bash

$ adduser spark-client # 유저 추가
$ vi /etc/ssh/sshd_config
port 2200X # 해당 포트를 열어준다.
$ service ssh start # 서비스를 restart

**Comment by hyu-leeky** [comment]
컨테이너를 만든 후에 사용자를 따로 생성해줘야 하는구나.
혹시 이미지 만들고 나서 container run 할때 자동으로 해주면 좋을듯 하기한데. 그건 다른 이슈로 한번 살펴보자.
그리고 포트의 경우에는 컨테이너에서 외부 포트로 포워딩 해주는 거니 컨테이너자체에서 2200X 에서 ssh 안해줘도 될것 같아.

즉 옵션이 -p 2200X:22 해서 컨테이너의 22번 포트를 호스트의 2200X 로 해주면, 위의 마지막 두 명령어는 필요없을것 같아.
