### ISSUE TITLE
rsa 키 를 사용한 ssh 기능 지원 필요

### ISSUE THREAD

**Issue by hyu-leeky** [kmubigdata/ubuntu-spark#6]
현재 컨테이너에서 사용자 생성 후 패스워드 기반의 ssh 만 가능.
이를 RSA public key 를 컨테이너 시작시에 인자로 줘서 RSA 기반 컨테이너 설정이 가능하도록 해야함

**Comment by KimJeongChul** [comment]
![1](https://cloud.githubusercontent.com/assets/10591350/26336143/dafc1f4e-3fab-11e7-921b-783be33dfb44.jpeg)
-v 옵션을 이용해 host의 파일을 mount 할 수 있다.
https://docs.docker.com/v1.11/engine/userguide/containers/dockervolumes/

```
$ sudo docker run -it --name spark-client2 --network spark-net  -p 22008:22 --add-host=master:10.0.2.2 --cpu-shares 1024 --memory 12g -v /home/kimjc/.ssh/id_rsa.pub:/tmp/id_rsa.pub kmubigdata/ubuntu-spark /bin/bash
# cat /tmp/id_rsa.pub >> /root/.ssh/authorized_keys
# cat /tmp/id_rsa.pub >> /home/유저명/.ssh/authorized_keys
# rm /tmp/id_rsa.pub
```

**Comment by hyu-leeky** [comment]
이방법도 괜찮네. 난 그냥 키 자체를 docker run 시에 인자로 전달하려고 했는데. 이것도 좋다. 우선 내가 인자 전달하는걸로 해서 PR 을 할테니, -v 옵션으로 하는건 정출이가 작업해줘.

**Comment by KimJeongChul** [comment]
#13  update run_spark PORT,IP,SSH 
pull-request 하였습니다.

**Comment by hyu-leeky** [comment]
@KimJeongChul 풀 리퀘스트 수고했어요. 이슈 클로즈는  PR 한뒤에 하는것 보다는, PR 통해서 코드리뷰 완료되고 마스터 브래니로 머지 된 후에 close 하도록 하자.
